---
- hosts: masters
  remote_user: ubuntu
  gather_facts: yes
  connection: ssh
  vars:
       calicoVer: v3.20

  tasks:
    - name: initialize the cluster
      shell: sudo kubeadm init --pod-network-cidr=10.244.0.0/16
      args:
        creates: cluster_initialized.txt

    - name: give non-root users access to use kubeadm
      shell: mkdir -p $HOME/.kube 

    - name: give non-root users access to use kubeadm
      shell: sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config 

    - name: give non-root users access to use kubeadm
      shell: sudo chown $(id -u):$(id -g) $HOME/.kube/config               

    - name: install Pod network
      shell: sudo kubectl apply -f https://docs.projectcalico.org/{{ calicoVer }}/manifests/calico.yaml 
        
    - name: Get the token for joining the worker nodes
      shell: kubeadm token create --print-join-command
      register: kubernetes_join_command

    - name: Get join command
      debug: 
        msg: "{{ kubernetes_join_command.stdout }}"

    - name: Copy join command to local file.
      local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777

