apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-clusteradmin
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cr-maintainer
rules:
- verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  resources: ["pods"]
  apiGroups: [""]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rb-maintainer
  namespace: default
subjects:
- kind: ServiceAccount
  name: sa-clusteradmin
  namespace: default
roleRef:
  kind: ClusterRole
  name: cr-maintainer
  apiGroup: rbac.authorization.k8s.io
