apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    name: myapp-pod
spec:
  containers:
  - name: msg-api
    image: tmarroquin/myapp:latest
    ports:
    - name: msg-api
      containerPort: 8080
