apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  labels:
    name: myapp-service
    app: myapp
    type:  myapp-front-end
spec:
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 32136
  selector:
    type: myapp-front-end
  type: NodePort
