apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    name: mysql
spec:
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  selector:
    name: mysql
  type: ClusterIP
